# Generated by Django 6.0.3 on 2026-04-18 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0009_recurso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='planificador.clase'),
        ),
        migrations.AlterField(
            model_name='configuracionusuario',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='configuracionusuario',
            name='tema',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro')], default='dark', max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planificador.grado'),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('grado_nombre', models.CharField(blank=True, max_length=50)),
                ('materia', models.CharField(blank=True, choices=[('Matemáticas', 'Matemáticas'), ('Lenguaje', 'Lenguaje'), ('Ciencias Naturales', 'Ciencias Naturales'), ('Ciencias Sociales', 'Ciencias Sociales'), ('Educación Física', 'Educación Física'), ('Artes', 'Artes'), ('Música', 'Música'), ('Inglés', 'Inglés')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('anio', models.IntegerField(default=2026)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='planificador.curso'),
        ),
    ]
