# Generated by Django 6.0.3 on 2026-04-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0011_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='objetivos',
            field=models.TextField(blank=True),
        ),
    ]
