# Generated by Django 6.0.3 on 2026-05-04 00:46

import planificador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0015_horario_academico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioacademico',
            name='hora_fin_jornada',
            field=models.TimeField(default=planificador.models._default_jornada_fin),
        ),
        migrations.AlterField(
            model_name='horarioacademico',
            name='hora_inicio_jornada',
            field=models.TimeField(default=planificador.models._default_jornada_inicio),
        ),
    ]
