# Generated by Django 6.0.3 on 2026-05-11 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0017_simplify_curso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='materia',
            field=models.CharField(blank=True, choices=[('Matemáticas', 'Matemáticas'), ('Lenguaje', 'Lenguaje'), ('Ciencias Naturales', 'Ciencias Naturales'), ('Ciencias Sociales', 'Ciencias Sociales'), ('Educación Física', 'Educación Física'), ('Artes', 'Artes'), ('Música', 'Música'), ('Inglés', 'Inglés')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='clase',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clase',
            index=models.Index(fields=['usuario', 'fecha'], name='planificado_usuario_7d186a_idx'),
        ),
        migrations.AddIndex(
            model_name='clase',
            index=models.Index(fields=['usuario', 'estado'], name='planificado_usuario_434fb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(fields=('usuario', 'nombre'), name='curso_unique_per_user'),
        ),
    ]
