# Generated by Django 6.0.3 on 2026-05-23 03:50

import planificador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0019_recurso_curso_prompt_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=planificador.models._recurso_upload_path),
        ),
    ]
