# Generated by Django 6.0.3 on 2026-05-24 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0023_remove_annual_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionusuario',
            name='hora_recordatorio_preferida',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
        migrations.AddField(
            model_name='configuracionusuario',
            name='recibir_recordatorio_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionusuario',
            name='ultimo_recordatorio_enviado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
