# Generated by Django 6.0.3 on 2026-05-24 23:37

import planificador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0024_email_reminder_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='anio',
            field=models.IntegerField(default=planificador.models._anio_actual),
        ),
    ]
