# Generated by Django 6.0.3 on 2026-06-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificador', '0028_clase_cancelada'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='planificado_usuario_fd366d_idx',
            old_name='notif_user_leido_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='planificado_usuario_7a3050_idx',
            old_name='notif_user_fecha_idx',
        ),
        migrations.AddField(
            model_name='clase',
            name='es_hora_libre',
            field=models.BooleanField(db_index=True, default=False, help_text='Bloque marcado por el docente como hora libre (sin clase).'),
        ),
    ]
